baseURL: "https://oliviatrager.github.io"
title: PaperMod
paginate: 5
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: ":gb:"
    languageAltTitle: English
    title: Olivia Trager
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: About
          url: about/
          weight: 10

  de:
    languageName: ":de:"
    languageAltTitle: Deutsch
    weight: 2
    title: Olivia Trager
    menu:
      main:
        - name: Artikel
          url: archives
          weight: 5
        - name: Suche
          url: search/
          weight: 10
        - name: Über mich
          url: about/
          weight: 7
    
    homeInfoParams:
        Title: "Erhalten Sie Ihre Staatsbürgerschaft in Deutschland"
        Content: >
          Hallo, ich bin Olivia, eine Imigrationsanwältin aus Berlin. 
          
          Ich kann Ihnen helfen mit Ihrem 

          -  **Visum** 

          - **Arbeitserlaubnis**

          - **Familienzusammenführung**

          - **Staatsbürgerschaft** 

          - **Aufenthaltserlaubnis**

          - und mehr

          

        enabled: true
        # title: Olivia Trager
        # imageUrl: "https://github.com/OliviaTrager/oliviatrager.github.io/blob/main/resources/_gen/images/profile.jpg?raw=true"
        # subtitle: "Ihre vertrauenswürdige Einwanderungsanwältin in Berlin"
        

  fr:
        languageName: ":fr:"
        languageAltTitle: French
        weight: 2
        title: Olivia Trager
        menu:
          main:
            - name: Articles
              url: archives
              weight: 5
            - name: Recherche
              url: search/
              weight: 10
            - name: À propos
              url: about/
              weight: 7
        profileMode:
            enabled: true
            title: Olivia Trager
            imageUrl: "https://github.com/OliviaTrager/oliviatrager.github.io/blob/main/resources/_gen/images/profile.jpg?raw=true"
            imageTitle: ProfileMode image
            # imageWidth: 120
            # imageHeight: 120
            subtitle: "Votre avocat en immigration de confiance à Berlin"
            buttons:
                - name: Email
                  url: mailto:renekuhn@posteo.de
  #hebrew:
  he:
    title: Olivia Trager
    weight: 4
    languageName: ":israel:"
    languageAltTitle: Hebrew
    menu:
      main:
        - name: מאמרים
          url: archives
          weight: 5
        - name: חיפוש
          url: search/
          weight: 10
        - name: אודות 
          url: about/
          weight: 7
    profileMode:
        enabled: true
        title: Olivia Trager
        imageUrl: "https://github.com/OliviaTrager/oliviatrager.github.io/blob/main/resources/_gen/images/profile.jpg?raw=true"
        imageTitle: ProfileMode image
        # imageWidth: 120
        # imageHeight: 120
        subtitle: "העורך דין להגירה האמין שלך בברלין"
        buttons:
            - name: Blog
              url: posts
            - name: Email
              url: mailto:renekuhn@posteo.de


  es:
      languageName: ":es:"
      languageAltTitle: Spanish
      weight: 2
      title: Olivia Trager
      menu:
        main:
          - name: Artículos
            url: archives
            weight: 5
          - name: Búsqueda
            url: search/
            weight: 10
          - name: Acerca de
            url: about/
            weight: 7
      profileMode:
          enabled: true
          title: Olivia Trager
          imageUrl: "https://github.com/OliviaTrager/oliviatrager.github.io/blob/main/resources/_gen/images/profile.jpg?raw=true"
          subtitle: "Su abogado de inmigración de confianza en Berlín"
          buttons:
              - name: Email
                url: mailto:renekuhn@posteo.de

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Olivia Tragers Blog"
  author: Olivia Trager
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  # comments: false
  images: ["papermod-cover.png"]

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Get your citizenship in Germany"
    Content: >
      Hello, I am Olivia an imigration Layer from Berlin. 
      
      I can help you with your 

      -  **visa** 

      - **work permit**

      - **family reunion**

      - **citizenship** 

      - **residence permit**

      - and more




  socialIcons: # optional
          - name: "LinkedIn"
            url: "https://de.linkedin.com/in/olivia-trager-2a7bbb193"
          - name: "Email"
            url: "mailto:renekuhn@posteo.de"
          - name: "phone"
            url: "https://wa.me/4915238970333"

  editPost:
    URL: "https://github.com/OliviaTrager/oliviatrager.github.io/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  # assets:
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
